services:
  db:
#    image: postgres:latest
    build:
      context: .
      dockerfile: database.Dockerfile
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: url
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  url-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS:
        -Xms256M
        -Xmx2G
      SPRING_PROFILES_ACTIVE: local
      DB_NAME: url
      DB_URL: jdbc:postgresql://db:5432/url
      DB_USER: user
      DB_PASSWORD: password
      DB_PORT: 5432
      ports:
        -8080:8080
    depends_on:
      db:
        condition: service_started