services:
  db:
#    image: postgres:latest
    build:
      context: .
      dockerfile: database.Dockerfile
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
  url-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS:
        -Xms256M
        -Xmx2G
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES}
      DB_NAME: ${DB_NAME}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    ports:
      - 8080:8080
    depends_on:
      - db
    stdin_open: true
    tty: true
