spring:
  application:
    name: url-app
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class: org.postgresql.Driver
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
logging:
  level:
    sql: INFO

kafka:
  bootstrap-servers: kafka:29092

# cron
schedulers:
  # every minute
  url-delete: "0 * * * * *"