spring:
  application:
    name: url-app
  datasource:
    url: jdbc:h2:~/db
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    sql: INFO

